package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TarefaFomento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String grupoJbpm;
	private java.lang.Long usuarioId;
	private java.lang.String tipoAcao;
	private java.lang.String numeroAnoAcao;
	private java.lang.Long fundId;
	private java.lang.String siglaAcao;

	public TarefaFomento() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getGrupoJbpm() {
		return this.grupoJbpm;
	}

	public void setGrupoJbpm(java.lang.String grupoJbpm) {
		this.grupoJbpm = grupoJbpm;
	}

	public java.lang.Long getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(java.lang.Long usuarioId) {
		this.usuarioId = usuarioId;
	}

	public java.lang.String getTipoAcao() {
		return this.tipoAcao;
	}

	public void setTipoAcao(java.lang.String tipoAcao) {
		this.tipoAcao = tipoAcao;
	}

	public java.lang.String getNumeroAnoAcao() {
		return this.numeroAnoAcao;
	}

	public void setNumeroAnoAcao(java.lang.String numeroAnoAcao) {
		this.numeroAnoAcao = numeroAnoAcao;
	}

	public java.lang.Long getFundId() {
		return this.fundId;
	}

	public void setFundId(java.lang.Long fundId) {
		this.fundId = fundId;
	}

	public java.lang.String getSiglaAcao() {
		return this.siglaAcao;
	}

	public void setSiglaAcao(java.lang.String siglaAcao) {
		this.siglaAcao = siglaAcao;
	}

	public TarefaFomento(java.lang.Long id, java.lang.String grupoJbpm,
			java.lang.Long usuarioId, java.lang.String tipoAcao,
			java.lang.String numeroAnoAcao, java.lang.Long fundId,
			java.lang.String siglaAcao) {
		this.id = id;
		this.grupoJbpm = grupoJbpm;
		this.usuarioId = usuarioId;
		this.tipoAcao = tipoAcao;
		this.numeroAnoAcao = numeroAnoAcao;
		this.fundId = fundId;
		this.siglaAcao = siglaAcao;
	}

}